### ISSUE TITLE
Put the repo url instead of the demo url in the npm publication page

### ISSUE THREAD

**Issue by baptistemanson** [camwest/react-slot-fill#1]
Hi,

I really liked your presentation during react conf! But I have a hard time to find back your github. The npm package lists the demo instead of the repo, which I think is not the usual practice. Otherwise a big thank you for this lib!

Cheers,

**Comment by camwest** [comment]
Ah this is interesting. There is a "homepage" key in package.json which I guess npm uses. But create-react-app uses for a different purpose. I'll put a link to the github repo on the demo at the top.

**Comment by nickyhajal** [comment]
This happened to me to! Took awhile to find the repo :)

Watched the presentation over the stream - stoked for Slot-Fill, thanks for your work on it!

**Comment by camwest** [comment]
As a quick fix I deployed a github link to the demo header. https://github.com/camwest/react-slot-fill
