### ISSUE TITLE
Propagate props into Slot's div wrapper.

### ISSUE THREAD

**Issue by AntonPuko** [camwest/react-slot-fill#12]
Hi, Thanks for the lib. For React 15.4 you wrap Slot's fill with `<div>`, it'd be nice to propagate some props like `style` and `className` to that div. it's useful when we pass many fills in one slot to be able to align them with the styles.

**Comment by camwest** [comment]
@AntonPuko what do you think about doing this?

```jsx
<Slot name="MySlot">
  {items => <div className="my-class">{items}</div>}
</Slot>
```

That currently works today and avoids us having to expand the Slot property API.

**Comment by AntonPuko** [comment]
ah, didn't think about that. Sounds good, thanks
