### ISSUE TITLE
Getting "ReferenceError: mitt is not defined" in v1.0.0-alpha.11

### ISSUE THREAD

**Issue by tommyschmiedel** [camwest/react-slot-fill#14]
Seems like the "module" target bundle doesn't import mitt, which results in the error "ReferenceError: mitt is not defined". Is this a bug or am I missing something?

I set up a simple example project and followed the usage notes. I use Webpack 2 for bundling. Please let me know if you need any additional info!

Thanks!

**Comment by camwest** [comment]
@tommyschmiedel yeah I have a build that fixes this but I need to publish it! I should do it in the next day or so.

**Comment by tommyschmiedel** [comment]
Nice to hear, thanks for your great work!

**Comment by camwest** [comment]
@tommyschmiedel I published alpha.12 can you test it and let me know if it fixes the issue for you?

**Comment by tommyschmiedel** [comment]
@camwest yeah, I can confirm that this fixes the issue. Thanks!

**Comment by camwest** [comment]
great ty for confirming.
