### ISSUE TITLE
Default component if slot not filled

### ISSUE THREAD

**Issue by natew** [camwest/react-slot-fill#19]
Would be useful. Could be:

```js
<Slot name="name" defaultComponent={() => <button />} />
```

**Comment by gorangajic** [comment]
you can do something like

```jsx
<Slot name="name">
    {fills => (fills.length === 0 ? <DefaultButton> : <div>{fills}</div>)}
</Slot>
```

**Comment by camwest** [comment]
Yeah I'd rather not increase the API surface unless it's really a huge value add. @natew what do you think about the proposed workaround?

**Comment by hinok** [comment]
@camwest Is there any way to avoid unmount / mount in such case?
Look at the demo: https://codesandbox.io/s/rm4v4vy3jm

If you switch from `Home` -> `Schedule`, `<Header />` component is only re-rendered once.
If you switch `to/from` `Roster`, `<Header />` is unmounted and mounted again which I'd like to avoid.
