### ISSUE TITLE
Current npm builds contain "const"

### ISSUE THREAD

**Issue by otbe** [camwest/react-slot-fill#20]
Hi,

Im struggling with some older IE versions (IE10) and react-slot-fill. It seems to me that both builds distributed via npm contains a const declaration:
```
const __assign = Object.assign || function (target) {
    for (var source, i = 1; i < arguments.length; i++) {
        source = arguments[i];
        for (var prop in source) {
            if (Object.prototype.hasOwnProperty.call(source, prop)) {
                target[prop] = source[prop];
            }
        }
    }
    return target;
};
```
which will fail with syntax errors in older browsers. I guess this code snippet is TypeScript related.

Any advice how to fix this?

Thanks!

**Comment by camwest** [comment]
@otbe did this get resolved?

**Comment by gorangajic** [comment]
I can confirm that it works now fine with `2.0.0`

**Comment by camwest** [comment]
OK thanks @gorangajic
