### ISSUE TITLE
"ReferenceError: mitt is not defined" after upgrading to 1.0.2

### ISSUE THREAD

**Issue by dmr** [camwest/react-slot-fill#28]
After updating to 1.0.2 I receive import errors "ReferenceError: mitt is not defined"

![image](https://user-images.githubusercontent.com/128286/31599769-07664396-b254-11e7-8b3c-6d0cdd6ba52c.png)

Does this has to do with this commit?
https://github.com/camwest/react-slot-fill/commit/f4087870aa3f74b86cb55f882e9f398586800256

**Comment by MatthieuLemoine** [comment]
The mitt import is missing in `lib/rsf.es.js` which is picked by webpack because of `"module": "lib/rsf.es.js"` in `package.json`.

If you set module to lib/rsf.js, you will have another error `mitt is not a constructor` as mitt also specify module in its `package.json`.

**Comment by MatthieuLemoine** [comment]
I think a rebuild should do the trick.

**Comment by hannahjin** [comment]
Having the same problem. I ran `yarn build` but that didn't resolve the issue.

**Comment by MatthieuLemoine** [comment]
@hannahjin You have to run the prepublish script instead.

**Comment by MatthieuLemoine** [comment]
Even with the import statement you will have the following error `mitt is not a constructor`. 

The problem is that if you use the ES module `rsf.es.js` it will import the mitt ES module `mitt.es.js` (webpack will do that by default). So in `Provider`, it should be `import mitt from 'mitt'` instead of `import * as mitt from 'mitt'`. 

But if you use `rsf.js` it will import `mitt.js` and then it should be `import * as mitt from 'mitt'`.

**Comment by MatthieuLemoine** [comment]
As a workaround, you can add the following to your webpack conf to force the usage of the umd build : 

```javascript
resolve : {
    mainFields : ['umd:main', 'module', 'main'],
},
```

**Comment by dmr** [comment]
So you say that my webpack config is the problem?

Is this a mitt issue or a react-slot-fill issue?

**Comment by dmr** [comment]
Sorry but I don't really understand the issue yet

**Comment by MatthieuLemoine** [comment]
The missing import is a react-slot-fill build issue.

The fact that it still doesn't work with the import is a mitt issue.

You can use the above workaround to make it work with webpack until this issue is fixed.

**Comment by hannahjin** [comment]
The prepublish script is not part of the package. `mitt` does appear in my `yarn.lock`, but I see that exact error in the picture.

**Comment by MatthieuLemoine** [comment]
#31 should fix this issue.
