### ISSUE TITLE
Compare Slot/Fill to React 16 Portals?

### ISSUE THREAD

**Issue by MMRandy** [camwest/react-slot-fill#33]
Can you provide a brief description of pro/cons for using this repo vs using Portals in React 16?

Very cool concepts here btw, dynamic component extensibility would certainly be useful imo.

Thanks.

**Comment by camwest** [comment]
I think we could probably refactor react-slot-fill to use React 16 Portals but I'm not 100% sure as I haven't had time to try it yet.

Here is the primary difference that I can see:

* **React DOM Portals** allow you to render React children into a DOM node that exists outside the DOM hierarchy of the parent component
* **React Slot Fill Components** allow you to render React children into another location in the current React sub-tree that isn't a direct descendant.

## React DOM Portal example:

Given the following DOM Nodes:

- div#app
- div#modal

```typescript
class App extends React.Component {
  render() {
    return (
      <div>
        <h1>Hello World</h1>
        {ReactDOM.createPortal(this.props.children, document.getElementById('modal'))}
      </div>
    );
  }
}

React.render(<App>Modal Content</App>, document.getElementId('app'));
```

In this example the text "Modal Content" would be appended to div#modal.

React Slot Fill Components Example:

Given the following dom nodes:

- div#app

```typescript
import {Provider, Slot, Fill} from 'react-slot-fill';

class List extends React.Component {
  render() {
    return (
      <ul>
        {this.props.items.map(item => <ListItem item={item} />}
      </ul>
    )
  }
}

class ListItem extends React.Component {
    state = { showing: false };
    handleClick = () => {
      this.setState({ showing: true });
    }

    handleHideModal = () => {
      this.setState({ showing: false });
    }

  render() {
    return (
      <li>
        {this.state.showing &&
          <Fill name="modal">Showing {this.props.item}
            <button onClick={this.handleHideModal}>Hide</button>
          </Fill>
        }
        {this.props.item}
      </li>
    );
  }
}

class App extends React.Component {
  render() {
    return (
      <Provider>
        <List items={["one", "two", "three"]} />
        <div className="modal">
          <Slot name="modal" />
        </div>
      </Provider>
    );
  }
}

React.render(<App />, document.getElementId('app'));
```

In this example you can see how react-slot-fill doesn't interact with dom nodes outside of the React subtree. Instead you can see how a deeply nested React Component (in this case ListItem) can render a child into a higher level context. 

Hopefully this answers your question!

**Comment by MMRandy** [comment]
Certainly does, thanks for the quick, detailed response.  Seems like a Portal's ability to inject components outside the current tree would be a plus, but love your ideas here.  Thanks!

**Comment by camwest** [comment]
Yeah totally! I think they are complimentary.
